-- MySQL Script generated by MySQL Workbench
-- Sun Jan 16 15:43:30 2022
-- Model: vipdrinks    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `measure` INT NULL,
  `price` DECIMAL(10,2) NULL,
  `short_description` VARCHAR(100) NULL,
  `long_description` VARCHAR(300) NULL,
  `brand` VARCHAR(45) NULL,
  `stock` INT NULL,
  `disocunt` DECIMAL(3,2) NULL,
  `raiting` INT NULL,
  `category` VARCHAR(45) NULL,
  `subcategory` VARCHAR(45) NULL,
  `luxury` INT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `country` VARCHAR(45) NULL,
  `img` VARCHAR(200) NULL,
  `birthday` DATE NULL,
  `profile` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `idCart` INT NOT NULL,
  `Fk_idUser` INT NULL,
  `Fk_idProduct` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `idUser_idx` (`Fk_idUser` ASC) VISIBLE,
  INDEX `idProduct_idx` (`Fk_idProduct` ASC) VISIBLE,
  CONSTRAINT `Fk_User`
    FOREIGN KEY (`Fk_idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_idProduct`
    FOREIGN KEY (`Fk_idProduct`)
    REFERENCES `mydb`.`products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idAdress` INT NOT NULL,
  `Fk_idUser` INT NULL,
  `street` VARCHAR(45) NULL,
  `street_number` INT NULL,
  `localty` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`idAdress`),
  INDEX `idUser_idx` (`Fk_idUser` ASC) VISIBLE,
  CONSTRAINT `Fk_idUser`
    FOREIGN KEY (`Fk_idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_method` (
  `idPayment_method` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment_method`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idOrder` INT NOT NULL,
  `idUser` INT NULL,
  `idPayment_method` INT NULL,
  `idAdress` INT NULL,
  `total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idAdress_idx` (`idAdress` ASC) VISIBLE,
  INDEX `idPayment_method_idx` (`idPayment_method` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPayment_method`
    FOREIGN KEY (`idPayment_method`)
    REFERENCES `mydb`.`payment_method` (`idPayment_method`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdress`
    FOREIGN KEY (`idAdress`)
    REFERENCES `mydb`.`address` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
